[package]
name = "dllwalk"
version = "0.1.0"
authors = ["Thibaut Durand"]
edition = "2021"


[dependencies]
bindings = { path = "bindings" }

clap = { version = "3.0.13", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.14"
nom = "6.0"
regex = "1.5.4"
windows = "0.18"
